### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by barbogast**

### CODE REVIEW

**Comment by barbogast** [comment]
I had to add `typescript` as a dependency. All projects except `website-react` upgrade without problems. `website-react` is so far behind that this probably doesn't make it worse.

**Comment by yamov** [comment]
Why did you have to add TS to dependencies in this repo?
Also were there any new rules worthy of enabling in the updated plugins?

**Comment by barbogast** [comment]
> Why did you have to add TS to dependencies in this repo?
It crashed without it.
> Also were there any new rules worthy of enabling in the updated plugins?
I didn't check, don't wanna work on it right now. Can we still merge? Or is it a blocker?

**Comment by yamov** [comment]
> It crashed without it.

Strange. Did this repo crash? 🤔 What exactly is the crash in this case?

**Comment by barbogast** [comment]
Will follow up.

**Comment by barbogast** [comment]
I did check the packages and couldn't find new rules that are interesting for us.

I'm not sure about typescript-eslint, though. The change-log shows several changes, but I'm not sure if they are relevant for us: https://github.com/typescript-eslint/typescript-eslint/releases. @yamov Do you know that from the top of your head, or should I dig depper?

**Comment by yamov** [comment]
Nope, wouldn't be able to answer from the top of my head, will also have to get into details.
Anyways, the relevance of the rules should probably be decided by a person updating the plugin. It will always be subjective and is probably fine.

**Comment by barbogast** [comment]
Alright, `typescript` is now a peer dependency. PR with new rules will follow once this is merged.

**Pull request merged**
